spring.application.name=config-service
server.port=9999
spring.cloud.discovery.enabled=true
eureka.instance.prefer-ip-address=true
spring.cloud.config.server.git.uri=https://github.com/YOUHAD08/microservices-config.git
eureka.client.service-url.defaultZone=${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
# Exposes all Actuator endpoints over HTTP (health, metrics, env, etc.)
# Restrict this in production (e.g. include=health,info)
management.endpoints.web.exposure.include=*
